widget redesign
lblod/ember-rdfa-editor-standard-template-plugin pull request #18
Opened 2022-04-14 13:22 UTC by Asergey91

2022-04-22 11:44 UTC, Dietr approved these changes

2022-04-22 17:47 UTC, nvdk commented on tests/integration/components/standard-template/template-card-test.js
> +import { module, test } from 'qunit';
remove default tests

2022-05-02 08:40 UTC, benjay10 commented
I don't have an "Approve" button, but I approve anyway. :)

Please also add a label to this PR!

2022-05-02 09:35 UTC, lagartoverde commented
Ok things to consider
- Maybe when there are no items in the menu we should hide it?
- Maybe we should give the user some feedback that he has inserted something? closing the menu or anything
- The insert links also should have the cursor as a pointer and the hover property as we have on the invoegen one

2022-05-05 09:34 UTC, nvdk requested changes
this seems to be a bit of a regression. I can't insert templates into an empty document?

2022-05-05 15:06 UTC, merged